"""
Django settings for Cloudstream project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-bh!6c+k4^%$qli$w+v)p$x(2+2n77g)%oqiuyz*hcg=k(!m8&_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

aws_access_key_id='ASIAW3MD7KSFBTHCTZTF'
aws_secret_access_key='omZzsgvxxdTXFhQtm57Ti5dO04dOwpQaUv6llyyA'
aws_session_token='IQoJb3JpZ2luX2VjEHIaCXVzLXdlc3QtMiJIMEYCIQD5nmeCVZ7gxq80XpFIeet+tIqhp5nOSf8aBTytQEV4aAIhAIKoSJVdKRS8r/jlZx2mJ4oZrB3fb1fn4XBD29I7huHLKq4CCDoQABoMNDcxMTEyNTY5OTk0IgxYKA7A3FQKAbOk5RcqiwL4qm0zXWmPfh6fLorTI+1NZvnBcyYtxWfdnawV+6AfPGi6fG627a3S/8YIgbgOcmI3B5aouwlxPf0kUn3wAT6cta9+Jr3Go/I0MRDR2jfF3ba9qXSCG2EFIkAclZi1xoklXgSXwGgarMyoLb3FVy8FyNitN7X9OWS7tbnu0WglN3RCdOVsH/dQP9D+JgtbK3WomuSEgc1GadU9CGHKZspV1Bexsqvly+ToniCwaph536HhLXsPaJq853nXKt2C7IA5j5HonZR3EAuE+OHyFUXqclM7EUdoN9A+P5qSHCmHICHQlY7v4iE2RiDxlsV4KJVwQH4Q+89rCbVPjMtp+5MOJm1rVmkPaJ5Qcl0wgcOkywY6nAGuwJENEniS5310GA203ja4WQF0uqCxS9v6GMhZXMEPA8Ywu8IGaEs4gPAMZi+0nGxtCvNqtP22jr3RLMHhNoPCRS68cPCPZihfZ9CvMppxQh4KVElYOUeulzX1nUwZM0xZkyzWLGKDFbIIz6Lt3Roiw7IUXzQ5svBU9Oxi0rdOPji3cQ45X8BgPx1CKm4T6OpEDkTirlK8eYtRkeI='
AWS_ACCESS_KEY_ID = aws_access_key_id
AWS_SECRET_ACCESS_KEY = aws_secret_access_key
AWS_SESSION_TOKEN = aws_session_token
AWS_REGION = 'us-east-1' # Check your actual region
DYNAMO_TABLE = 'CloudStreamData'
AWS_RAW_BUCKET = 'vinayrawvidscloudstream'      # The bucket you upload to
AWS_PROCESSED_BUCKET = 'vinayfinalvidscloudstream' # The bucket you watch from

# settings.py

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Dashboard'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Cloudstream.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Cloudstream.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
SESSION_ENGINE = "django.contrib.sessions.backends.signed_cookies"